"""digest_paper m2m; drop papers.digest_id

Revision ID: eaed2624a49d
Revises: 746ae717c347
Create Date: 2026-08-29 11:17:25.979708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaed2624a49d'
down_revision: Union[str, Sequence[str], None] = '746ae717c347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digest_paper',
    sa.Column('digest_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('paper_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['digest_id'], ['digests.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('digest_id', 'paper_id')
    )
    op.drop_constraint('papers_digest_id_fkey', 'papers', type_='foreignkey')
    op.drop_column('papers', 'digest_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('digest_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('papers_digest_id_fkey', 'papers', 'digests', ['digest_id'], ['id'])
    op.drop_table('digest_paper')
    # ### end Alembic commands ###
